services:
  pz-cheeseria-app:
    container_name: pz-cheeseria-app-container
    build: .
    image: pz-cheeseria-app:v1
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
